name: SwiftCI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          #- { scheme: 'netlaband', destination: 'platform=macOS' }
          - { scheme: 'Chart', destination: 'platform=iOS Simulator,OS=15.2,name=iPhone 8' }
    steps:
    - uses: actions/checkout@v2

    - name: Show Build Version
      run: xcodebuild -version

    # - name: Show Build Settings
    #   run: xcodebuild -scheme Chart -showBuildSettings

    # - name: Show Build SDK
    #   run: xcodebuild -scheme Chart -showsdks
      
    - name: Show Destinations
      run: xcodebuild -scheme '${{ matrix.run-config['scheme'] }}' -showdestinations

    #- name: Build
    #  run: swift build -v

    # - name: Run tests
    #   run: swift test --enable-code-coverage -v

    - name: build and test
      run: xcodebuild clean test -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary
        #- name: check against API breaking changes
        #  run: swift package diagnose-api-breaking-changes 0.5.0

    # - name: env review
    #   run: env

    - name: Verify formatting
      run: swiftformat --lint .
    
    - name: Prepare Code Coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/ChartPackageTests.xctest/Contents/MacOS/ChartPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov

    - name: Upload to CodeCov.io
      run: bash <(curl https://codecov.io/bash)
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
